name: jsonse
description: Serialize json object to dart object.
version: 1.0.0

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

environment: 
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  path: ^1.8.0
  args: ^2.3.0
  collection: ^1.15.0
  yaml: ^3.1.0
  pub_semver: ^2.1.0
  runtime:
    path: ../packages/runtime
