name: runtime
description: Provides behaviors and base types for packages that can use mirrors and be AOT compiled.
version: 1.0.0-9
homepage: https://stablekernel.com

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  collection: ^1.15.0

dev_dependencies:

